name: "Setup zmk build env"
description: "Setup zephyr sdk and initialize west workspace"
inputs:
  zephyr-sdk-version:
    description: "zephyr sdk version to setup"
    default: "0.17.0"
runs:
  using: "composite"
  steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
        cmake --version
        python3 --version
        dtc --version
      shell: bash

    - name: Install West and pre-commit
      run: |
        pip3 install --user -U west pyelftools grpcio-tools pre-commit
        echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
        source ~/.bashrc
      shell: bash

    - name: Cache Zephyr SDK
      id: cache-zephyr
      uses: actions/cache@v4
      with:
        path: /home/runner/zephyr-sdk-${{ inputs.zephyr-sdk-version }}
        key: zephyr-sdk-${{ inputs.zephyr-sdk-version }}-arm-zephyr-eabi

    - name: Download Zephyr SDK
      if: ${{ steps.cache-zephyr.outputs.cache-hit != 'true' }}
      run: |
        cd ~
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${{ inputs.zephyr-sdk-version }}/zephyr-sdk-${{ inputs.zephyr-sdk-version }}_linux-x86_64.tar.xz
        wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${{ inputs.zephyr-sdk-version }}/sha256.sum | shasum --check --ignore-missing
        tar xvf zephyr-sdk-${{ inputs.zephyr-sdk-version }}_linux-x86_64.tar.xz
      shell: bash

    - name: Install Zephyr SDK components
      run: |
        cd ~/zephyr-sdk-${{ inputs.zephyr-sdk-version }}
        ./setup.sh -h -c -t arm-zephyr-eabi
      shell: bash

    - uses: ./.github/actions/west-init

    - name: Verify setup
      run: |
        west zmk-build tests/zmk-config -n
      shell: bash

    - name: Install pre-commit hooks
      run: pre-commit install
      shell: bash
